site_name: 邦史-基于Bang Dream剧情的史传化同人创作
site_url: https://dioxanehsu.github.io/Bangraphy/
theme:
  name: windmill        
  language: zh        # 设置为中文（搜索插件和界面会变中文）
  palette:               # 调色板
    primary: indigo      # 主色调（顶栏颜色）
    accent: indigo       # 强调色（链接、按钮颜色）
  features:
    - navigation.tabs    # 开启顶部导航标签
    - navigation.sections # 侧边栏分组显示
    - search.highlight
nav:
  - 主页: index.md
  - 关于: about.md
  - 本纪: benji.md
  - 载记: zaiji.md
  - 志: zhi.md
  - 列传: liezhuan.md
extra:
  alternate:
    - name: 简体中文
      link: ./
      lang: zh
    - name: English
      link: ./en/
      lang: en
plugins:
  - search  # 默认的搜索插件一定要写上，否则搜索功能会失效
  - i18n:
      docs_structure: suffix  # 核心逻辑：通过文件名的后缀来区分语言
      fallback_to_default: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build_step: true
        - locale: en
          name: English
          build_step: true